import random # Sempre no topo do arquivo!
# funções e módulos
# sorteio de números
 
numero_random = random.randint(1, 30)
print(numero_random)

def sorteiame():
    '''
     aspas triplas descreve oq uma função faz
     algoritmo escolhe e retorna um numero 
    inteiro aleatorio no intervalo de um 1, 30
    '''
   
    import random
    numero_random = random.randint(1, 30)

    # print(numero_random)
    return numero_random
